# Generated by Django 4.1.3 on 2023-01-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskkit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskkitTaskQueue',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=40)),
                ('due', models.FloatField()),
            ],
            options={
                'db_table': 'taskkit_task_queue',
                'index_together': {('group', 'due')},
            },
        ),
    ]
