# Generated by Django 4.1.3 on 2023-04-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskkit', '0002_taskkittaskqueue'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='taskkittask',
            new_name='taskkit_tas_done_e2b997_idx',
            old_fields=('done', 'began'),
        ),
        migrations.RenameIndex(
            model_name='taskkittask',
            new_name='taskkit_tas_began_9de665_idx',
            old_fields=('began', 'group', 'due'),
        ),
        migrations.RenameIndex(
            model_name='taskkittask',
            new_name='taskkit_tas_name_5b69c2_idx',
            old_fields=('name', 'created'),
        ),
        migrations.RenameIndex(
            model_name='taskkittaskqueue',
            new_name='taskkit_tas_group_10a09a_idx',
            old_fields=('group', 'due'),
        ),
    ]
